---
- name: Create Authelia secrets
  containers.podman.podman_secret:
    name: "AUTHELIA_{{ item | basename }}"
    data: "{{ lookup('file', '{{ item }}') }}"
    skip_existing: true
  with_fileglob:
    - "secret/*"

- name: Copy Authelia config
  ansible.builtin.copy:
    mode: preserve
    src: conf/
    dest: "{{ quadlet_dir }}/authelia/"

- name: Copy Authelia Quadlet
  ansible.builtin.template:
    mode: preserve
    src: authelia.container
    dest: "{{ quadlet_dir }}/authelia.container"
