---
- name: Create LLDAP secrets
  containers.podman.podman_secret:
    name: "LLDAP_{{ item | basename }}"
    data: "{{ lookup('file', '{{ item }}') }}"
    skip_existing: true
  with_fileglob:
    - "secret/*"

- name: Copy LLDAP Quadlet
  ansible.builtin.template:
    src: lldap.container
    dest: "{{ quadlet_dir }}/lldap.container"
