[ ! -d "$XDG_DATA_HOME/zsh"  ] && mkdir "$XDG_DATA_HOME/zsh"
[ ! -d "$XDG_CACHE_HOME/zsh" ] && mkdir "$XDG_CACHE_HOME/zsh"

HISTFILE="$XDG_DATA_HOME/zsh/history"
HISTSIZE=2000 # Nr. commands to keep in HISTFILE.
SAVEHIST=2100 # Nr. commands to keep in memory for a session.
set -k                        # Allow comments in interactive shells.
setopt autocd                 # Change directory without `cd`.
setopt hist_expire_dups_first # Expire duplicate entries first when trimming history.
setopt hist_ignore_dups       # Don't record an entry that was just recorded.
setopt hist_ignore_space      # Don't insert cmds into hist if space is the leading char.
setopt hist_reduce_blanks     # Remove superfluous blanks in commands.
setopt share_history          # Share history between different instances of zsh.

autoload -U compinit && compinit -d $XDG_CACHE_HOME/zsh/zcompdump

source "$XDG_CONFIG_HOME/zsh/aliases.sh"

source "$XDG_DATA_HOME/zsh/antidote/antidote.zsh"
antidote load "$XDG_CONFIG_HOME/zsh/plugins.conf"

bindkey '^[[1;5C' forward-word   # Ctrl+Right.
bindkey '^[[1;5D' backward-word  # Ctrl+Left.
bindkey '^[[3~' delete-char      # Del.
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[[F' end-of-line       # End.
bindkey '^[[H' beginning-of-line # Home.

path+=("$CARGO_HOME/bin")
path+=("$GOPATH/bin")
