---
- name: Copy Caddy config
  ansible.builtin.copy:
    src: conf/
    dest: "{{ quadlet_dir }}/caddy/"
    mode: preserve

- name: Copy Caddy Quadlet
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - "*.container"
    - "*.volume"

- name: Copy Caddy socket
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ containers_home }}/.config/systemd/user/"
    mode: preserve
  with_fileglob:
    - "*.socket"
