---
- name: "Install ZSH"
  ansible.builtin.package:
    name:
      - zsh
  become: true

- name: "Install ZSH plugin manager"
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote.git
    dest: "{{ lookup('env', 'XDG_DATA_HOME') }}/zsh/antidote"
    version: HEAD # noqa: latest

- name: "Configure ZSH"
  block:
    - name: "Copy config directory"
      ansible.builtin.file:
        src: "{{ ansible_search_path[0] }}/conf"
        dest: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/zsh"
        state: link
    - name: "Symlink .zshenv"
      ansible.builtin.file:
        src: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/zsh/zshenv"
        dest: "{{ lookup('env', 'HOME') }}/.zshenv"
        state: link
    - name: "Symlink .zshrc"
      ansible.builtin.file:
        src: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/zsh/zshrc"
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: link

- name: "Set ZSH as the default shell"
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
  become: true
