BACKUP_PATHS="/dir1/path /dir2/path"
BACKUP_EXCLUDES=""
RETENTION_DAYS=7
RETENTION_WEEKS=3
RETENTION_MONTHS=2
RETENTION_YEARS=2
RESTIC_REPOSITORY=sftp:user@host:/remote/repository/path
SSH_PASSWORD='Password'
RESTIC_PASSWORD='Password'
