PATHS="/dir1/path /dir2/path"
EXCLUDED=""
KEEP_DAYS=7
KEEP_WEEKS=3
KEEP_MONTHS=2
KEEP_YEARS=2
RESTIC_REPOSITORY=sftp:user@host:/remote/repository/path
SSH_PASSWORD='Password'
RESTIC_PASSWORD='Password'
