---
- name: Root operations
  become: true
  become_user: root
  block:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - podman
          - ufw

    - name: 'Create user named "{{ containers_user }}"'
      ansible.builtin.user:
        name: "{{ containers_user }}"
        create_home: true
        groups:
          - "dialout"  # For the Zigbee Hub, that is a serial device.
        home: "{{ containers_home }}"
        shell: /sbin/nologin
        system: true

    - name: 'Add subuid and subgid to user named {{ containers_user }}'
      ansible.builtin.command: "usermod --add-subuids 200000-265535 --add-subgids 200000-265535 {{ containers_user }}"
      changed_when: true

    - name: 'Set permissions to home directory of user "{{ containers_user }}'
      ansible.builtin.file:
        group: root
        mode: "750"
        owner: "{{ containers_user }}"
        path: "{{ containers_home }}"

    - name: 'Enable linger for user named "{{ containers_user }}"'
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ containers_user }}"
        creates: '/var/lib/systemd/linger/{{ containers_user }}'

    - name: "Redirect HTTP and HTTPS ports to unprivileged ports"
      ansible.builtin.blockinfile:
        path: /etc/ufw/before.rules
        insertbefore: BOF
        block: |
          *nat
          :PREROUTING ACCEPT [0:0]
          -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
          -A PREROUTING -p udp --dport 443 -j REDIRECT --to-port 8443
          -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443
          -A OUTPUT -o lo -p udp --dport 443 -j REDIRECT --to-port 8443
          -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8443
          COMMIT
        append_newline: true
        backup: true
        validate: "iptables-restore --test %s"

    - name: "Set allowed IP ports"
      community.general.ufw:
        default: deny
        port: "{{ item }}"
        rule: allow
        state: enabled
      loop:
        - ssh  # Keep it above otherwise we get closed out!
        - "8080 proto tcp"
        - "8443"

- name: Containers operations
  become: true
  become_user: containers
  block:
    - name: Create Quadlet destination directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ quadlet_install_dir }}"
        state: directory

    - name: Install common Quadlets
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ quadlet_install_dir }}/{{ item | basename }}"
        mode: preserve
      with_fileglob:
        - "*.network"
        - "*.volume"

    - name: Install Quadlets
      ansible.builtin.include_role:
        name: quadlet
      vars: {quadlet_name: "{{ qname }}"}
      loop:
        - authelia
        - caddy
        - cloudflare-ddns
        - homeassistant
        - lldap
        - mealie
        - nextcloud
        - postfix
        - postgresql
        - restic
        - valkey
        - z2m
      loop_control:
        loop_var: qname

    - name: Reload systemd units
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
