---
- name: Copy Home Assistant Quadlet
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}/{{ item | basename }}"
    mode: preserve
  with_fileglob:
    - "*.container"
    - "*.volume"
