advanced:
  log_level: warning
  log_namespaced_levels:
    z2m:mqtt: warning
devices: devices.yaml
frontend:
  enabled: true
groups: groups.yaml
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
onboarding: false
serial: {}
version: 5
availability:
  enabled: true
